### ISSUE TITLE
Should MovingWindow drop dimensions for stepsize 0

### ISSUE THREAD

**Issue by felixcremer** [meggart/YAXArrays.jl#106]
When I apply a moving Window computation with step size zero I get something like the following as an inner array:

```julia
julia> tscube
YAXArray with the following dimensions
Lon                 Axis with 1 Elements from 0 to 0
Lat                 Axis with 1 Elements from 0 to 0
Time                Axis with 100 Elements from 2016-10-03T10:12:28 to 2020-02-09T10:12:44
Polarisation        Axis with 2 elements: VH VV 
Total size: 800.0 bytes
```

This is for a InDims with a MovingWindow of step 0 for Lat and Lon and added Axes for Time and Polarisation. 

Should YAXArray in the registration realise, that the inner dimension of lon and lat could be dropped or would this lead to confusion?

**Comment by meggart** [comment]
I personally would not drop the movingwindow dimension here. Can you shortly describe the use case, i.e. why do you use a zeros-size moving window instead of just omitting lon and lat in the InDims?

**Comment by felixcremer** [comment]
Yes you are right, I don't need the Moving Window for my use case.
