### ISSUE TITLE
Obtain axis values Lon, Lat, Time, from Cubes

### ISSUE THREAD

**Issue by lazarusA** [meggart/YAXArrays.jl#29]
Hello, 
it would be nice to be able to retrieve the values from a Cube `c` as in 

`c.lon, c.lat, c.time`

as a plus, integrating the altitude, if available,  would be also great :D, `c.alt`
Elevation matrix from NOAA http://www.ngdc.noaa.gov/mgg/global/global.html

**Comment by meggart** [comment]
This is fixed on latest master, you can access a cube's axis now with `getproperty` which is called by the dot notation
