### ISSUE TITLE
Allow symbols as Axis describtion in size function

### ISSUE THREAD

**Issue by felixcremer** [meggart/YAXArrays.jl#52]
Should we allow to specify the dimension in the size function as symbol?
This would look like this:
```julia
julia> size(cube, :X)
7500
```

This would make it easier to write generic code with the cubes and to be not as dependent of the right axis permutation.

We can achieve this with the following additional method definition.
I could prepare a PR for that. 
```julia
Base.size(a::YAXArray, desc::Symbol) = size(getdata(a), findAxis(desc, a))
```

**Comment by meggart** [comment]
Closed with #98
