### ISSUE TITLE
Should CubeTable warn when there is no common axis found?

### ISSUE THREAD

**Issue by felixcremer** [meggart/YAXArrays.jl#58]
CubeTable will combine cubes which have no common axes.  
This surprised me, because I tried to combine two cubes which had the same spatial axes but different  names (X,Y) vs (Lat,Lon). I only captured the error, because the number of elements of the cube table was too high. 
I think, that it might be helpful to throw a warning, when there are no common axis.

**Comment by meggart** [comment]
Yes, this sounds like a good idea. You would have to add the following code after [this line](https://github.com/meggart/YAXArrays.jl/blob/4de682d1a24ca66a9fd0945a0b8af4139b6b3931/src/DAT/dciterators.jl#L182)
````julia
if isempty(intersect(axnames...))
  @warn "Input cubes to the table do not share a common axis, please check the axis names"
end
````
I just don't have the time to make a PR right now, maybe you can squeeze this into #59 including a test if the warning is thrown?
