### ISSUE TITLE
mapCube does not match by axis name but by axis position?

### ISSUE THREAD

**Issue by noralinscheid** [meggart/YAXArrays.jl#69]
I have run into the following behaviour which has confused me: If I run `mapCube` on two cubes with different number of axes, and only use a subset of these axis as `InDims`, I understand that `mapCube` should iterate over all remaining axes. However if the cube axes do not have the same order among cubes, it seems the match is done by position rather than axis name (or for the same reason fails if axes do not have the same length).

Artificial example below: Data has dimensions time, scale, variable. The mask (x .> 0) only has dimensions time, scale. Scale and variable have the same length. If the axes are ordered correctly (`time, scale` as first two axes in both cubes), the masking works correctly on `scale` (on position 2, see `cout`). If the input data cube is ordered `time, var, scale`, the masking is done on the `var` axis (now on position 2) instead of `scale` (see `cout_perm`). 

If the two axes are not the same length (each length 2 here), the operation fails for indexing reasons.

Am I doing something wrong? Otherwise: I know in principle this is easy to fix using `permutedims` on the input cubes and only happens when two axes have the same length. But if one is not aware this easily slips unnoticed or takes up a lot of troubleshooting time because it causes silent errors that are hard to track. I think a safer behaviour would be either that `mapCube` automatically permutes the dimensions on input cubes to fit, or that a "human-readable" error is thrown if the dimensions (including axis names) of input cubes don't match. Otherwise it will be very hard to trace especially in high-dimensional datasets. 

Thanks!

```
t=1:10
# data with dimensions time, scale, variable
arr = reshape([sin.(t) sin.(t/2) sin.(t) sin.(t/2)], 10, 2, 2)

# mask with dimensions time, scale
arr_mask = hcat(replace(arr[:,:,1] .> 0, 0=> missing))

t = RangeAxis(:time, 1:size(arr,1))
x = RangeAxis(:scale, 1:size(arr,2))
y = RangeAxis(:var, 1:size(arr,3))

cube = YAXArray([t,x,y], arr)
cube_mask = YAXArray([t,x], arr_mask)

cube_mask.data

cout = mapCube((cube,cube_mask),
    indims=(InDims("time"),InDims("time")),
    outdims=OutDims("time")) do xout, xin, xmask 
    xout[:] = xin .* xmask
end

cout[scale=1].data    # all data <0 is masked correctly

cout_perm = mapCube((permutedims(cube,[1,3,2]),cube_mask),    # permuting input dimensions
    indims=(InDims("time"),InDims("time")),
    outdims=OutDims("time")) do xout, xin, xmask 
    xout[:] = xin .* xmask
end

cout_perm[scale=1].data    # mask was applied along dimension var, not scale
```

**Comment by meggart** [comment]
Probably related to #53
